### ISSUE TITLE
Help!!!Compile Error! In location libs/box_utils

### ISSUE THREAD

**Issue by helloxueen** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#96]
**why does run "python setup.py build_ext --inplace" compile /libs/box_utils and /libs/box_utils/cython_utils have error? I have tried R2CNN-PLUS-PLUS, R2CNN_Faster-RCNN and R2CNN_FPN, all of them have the same error!! Details is as follows.**

In file included from /home/ivis/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1824:0,
from /home/ivis/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
from /home/ivis/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
from rbbox_overlaps.cpp:449:
/home/ivis/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
#warning "Using deprecated NumPy API, disable it with "
^~~~~~~
rbbox_overlaps.cpp: In function ‘void __Pyx__ExceptionSave(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
rbbox_overlaps.cpp:5670:21: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
type = tstate->exc_type;
^~~~~~~~
curexc_type
rbbox_overlaps.cpp:5671:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
value = tstate->exc_value;
^~~~~~~~~
curexc_value
rbbox_overlaps.cpp:5672:19: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
tb = tstate->exc_traceback;
^~~~~~~~~~~~~
curexc_traceback
rbbox_overlaps.cpp: In function ‘void __Pyx__ExceptionReset(PyThreadState, PyObject, PyObject, PyObject*)’:
rbbox_overlaps.cpp:5679:24: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
tmp_type = tstate->exc_type;
^~~~~~~~
curexc_type
rbbox_overlaps.cpp:5680:25: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
tmp_value = tstate->exc_value;
^~~~~~~~~
curexc_value
rbbox_overlaps.cpp:5681:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
tmp_tb = tstate->exc_traceback;
^~~~~~~~~~~~~
curexc_traceback
rbbox_overlaps.cpp:5682:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
tstate->exc_type = type;
^~~~~~~~
curexc_type
rbbox_overlaps.cpp:5683:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
tstate->exc_value = value;
^~~~~~~~~
curexc_value
rbbox_overlaps.cpp:5684:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
tstate->exc_traceback = tb;
^~~~~~~~~~~~~
curexc_traceback
rbbox_overlaps.cpp: In function ‘int __Pyx__GetException(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
rbbox_overlaps.cpp:5739:24: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
tmp_type = tstate->exc_type;
^~~~~~~~
curexc_type
rbbox_overlaps.cpp:5740:25: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
tmp_value = tstate->exc_value;
^~~~~~~~~
curexc_value
rbbox_overlaps.cpp:5741:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
tmp_tb = tstate->exc_traceback;
^~~~~~~~~~~~~
curexc_traceback
rbbox_overlaps.cpp:5742:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
tstate->exc_type = local_type;
^~~~~~~~
curexc_type
rbbox_overlaps.cpp:5743:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
tstate->exc_value = local_value;
^~~~~~~~~
curexc_value
rbbox_overlaps.cpp:5744:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
tstate->exc_traceback = local_tb;

**Comment by helloxueen** [comment]
> **why does run "python setup.py build_ext --inplace" compile /libs/box_utils and /libs/box_utils/cython_utils have error? I have tried R2CNN-PLUS-PLUS, R2CNN_Faster-RCNN and R2CNN_FPN, all of them have the same error!! Details is as follows.**
> 
> In file included from /home/ivis/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1824:0,
> from /home/ivis/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
> from /home/ivis/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
> from rbbox_overlaps.cpp:449:
> /home/ivis/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
> #warning "Using deprecated NumPy API, disable it with "
> ^~~~~~~
> rbbox_overlaps.cpp: In function ‘void __Pyx__ExceptionSave(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
> rbbox_overlaps.cpp:5670:21: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
> type = tstate->exc_type;
> ^~~~~~~~
> curexc_type
> rbbox_overlaps.cpp:5671:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
> value = tstate->exc_value;
> ^~~~~~~~~
> curexc_value
> rbbox_overlaps.cpp:5672:19: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
> tb = tstate->exc_traceback;
> ^~~~~~~~~~~~~
> curexc_traceback
> rbbox_overlaps.cpp: In function ‘void __Pyx__ExceptionReset(PyThreadState, PyObject, PyObject, PyObject*)’:
> rbbox_overlaps.cpp:5679:24: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
> tmp_type = tstate->exc_type;
> ^~~~~~~~
> curexc_type
> rbbox_overlaps.cpp:5680:25: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
> tmp_value = tstate->exc_value;
> ^~~~~~~~~
> curexc_value
> rbbox_overlaps.cpp:5681:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
> tmp_tb = tstate->exc_traceback;
> ^~~~~~~~~~~~~
> curexc_traceback
> rbbox_overlaps.cpp:5682:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
> tstate->exc_type = type;
> ^~~~~~~~
> curexc_type
> rbbox_overlaps.cpp:5683:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
> tstate->exc_value = value;
> ^~~~~~~~~
> curexc_value
> rbbox_overlaps.cpp:5684:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
> tstate->exc_traceback = tb;
> ^~~~~~~~~~~~~
> curexc_traceback
> rbbox_overlaps.cpp: In function ‘int __Pyx__GetException(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
> rbbox_overlaps.cpp:5739:24: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
> tmp_type = tstate->exc_type;
> ^~~~~~~~
> curexc_type
> rbbox_overlaps.cpp:5740:25: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
> tmp_value = tstate->exc_value;
> ^~~~~~~~~
> curexc_value
> rbbox_overlaps.cpp:5741:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
> tmp_tb = tstate->exc_traceback;
> ^~~~~~~~~~~~~
> curexc_traceback
> rbbox_overlaps.cpp:5742:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’; did you mean ‘curexc_type’?
> tstate->exc_type = local_type;
> ^~~~~~~~
> curexc_type
> rbbox_overlaps.cpp:5743:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’; did you mean ‘curexc_value’?
> tstate->exc_value = local_value;
> ^~~~~~~~~
> curexc_value
> rbbox_overlaps.cpp:5744:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
> tstate->exc_traceback = local_tb;

Thank you ,I have passed the problem

**Comment by leeecheng** [comment]
I have the same problem. Could you tell me how to solve it ?

**Comment by leeecheng** [comment]
@helloxueen

**Comment by helloxueen** [comment]
> 
> 
> I have the same problem. Could you tell me how to solve it ?

you should use python 2.X version, you could create vitual environment for a choice

**Comment by leeecheng** [comment]
Ok, thanks. I had compiled successfully with warning instructions. Now, I can compile on python 3.7.5 version.
